# Feature constraints


# E:\SentinAL_Project\configs\monotonic_constraints.yaml

constraints:
  # Liquidity (More liquidity = Less Risk)
  current_ratio: -1
  quick_ratio: -1
  cash_flow_per_share: -1

  # Leverage (More debt = More Risk)
  debt_to_equity: 1
  debt_ratio: 1
  interest_coverage_ratio: -1  # Higher coverage is safer

  # Profitability (More profit = Less Risk)
  net_profit_margin: -1
  return_on_equity: -1
  
  # Operational
  asset_turnover: -1